version: '3'
services:
  app:
    container_name: GoGround
    build: .
    ports: 
      - 8081:8080 
    restart: on-failure
    depends_on:
      - goground-mysql          
    networks:
      - goground


  goground-mysql:
    image: mysql:5.7
    container_name: goground_db_mysql
    ports: 
      - 3307:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - $PWD/database_mysql:/var/lib/mysql
    networks:
      - goground
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - goground-mysql
    environment:
      - PMA_HOST=goground-mysql
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9091:80
    restart: always
    networks:
      - goground


volumes:
  api:
  database_mysql:                  

# Facilitate communication between containers
networks:
  goground:
    driver: bridge